### ISSUE TITLE
Can't import compare, measure

### ISSUE THREAD

**Issue by pjakobsen** [Karlheinzniebuhr/pythonbenchmark#2]
Python 3.5.1

`>>> from pythonbenchmark import compare

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/peder/.virtualenvs/fasttrade/lib/python3.5/site-packages/pythonbenchmark/**init**.py", line 1, in <module>
    from pythonbenchmark import compare, measure
ImportError: cannot import name 'compare'`

**Comment by Karlheinzniebuhr** [comment]
Thanks for reporting, I now made an update, could you try with the last version here from github? because in pip its not updated yet.

**Comment by Karlheinzniebuhr** [comment]
It works for me, I've updated the package in pip, should work within an hour,
Cheers

**Comment by pjakobsen** [comment]
Sorry for the late reply.  Works for me too.  Thanks for the quick response, great little library.
